# Generated by Django 2.2.2 on 2019-09-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
