# Generated by Django 2.2.2 on 2019-10-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0005_auto_20190927_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
