# Generated by Django 2.2.2 on 2019-10-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0007_fish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='HarvestDate',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='fish',
            name='immersiveDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
