# Generated by Django 2.2.2 on 2019-10-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0009_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='amount',
        ),
    ]
