# Generated by Django 2.2.2 on 2019-10-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0011_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='number',
            new_name='amount',
        ),
    ]
