# Generated by Django 2.2.2 on 2019-10-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0012_auto_20191029_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
