# Generated by Django 2.2.2 on 2019-10-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0014_debtors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtors',
            name='quantity',
            field=models.IntegerField(max_length=50),
        ),
    ]
