# Generated by Django 2.2.2 on 2019-10-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsapp', '0016_auto_20191029_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
